apiVersion: rbac.authorization.k8s.io/v1

kind: RoleBinding
metadata:
  name: admin-jenkins
  namespace: poc  # évidemment le role d'admin de Jenkins est restreint au namespace poc.
subjects:
  # Note : le User ici est bienun User humain. Le top serait de pouvoir se faire passer pour le ServiceAccount jenkins,
  # qui existe déjà. Ca doit être faisable mais pour l'insant bon ben voilà, jenkins a deux comptes pour le moment.
  - kind: User
    name: jenkins
    apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io